export interface AvatarEntry {
  id: number;
  file: string;
  original: string;
  label: string;
  slug: string;
  alt: string;
}

export enum AvatarCategory {
  face = "face",
  left = "left",
  right = "right",
  body = "body",
  hat = "hat",
}

export type AvatarManifest = Record<AvatarCategory, AvatarEntry[]>;

export const avatarManifest: AvatarManifest = {
  face: [
    {
      id: 1,
      file: "avatar/face/001.webp",
      original: "big_mouth.webp",
      label: "Big Mouth",
      slug: "big-mouth",
      alt: "Big Mouth",
    },
    {
      id: 2,
      file: "avatar/face/002.webp",
      original: "bored_mouth.webp",
      label: "Bored Mouth",
      slug: "bored-mouth",
      alt: "Bored Mouth",
    },
    {
      id: 3,
      file: "avatar/face/003.webp",
      original: "duck_mouth.webp",
      label: "Duck Mouth",
      slug: "duck-mouth",
      alt: "Duck Mouth",
    },
    {
      id: 4,
      file: "avatar/face/004.webp",
      original: "grinch.webp",
      label: "Grinch",
      slug: "grinch",
      alt: "Grinch",
    },
    {
      id: 5,
      file: "avatar/face/005.webp",
      original: "happy_mouth.webp",
      label: "Happy Mouth",
      slug: "happy-mouth",
      alt: "Happy Mouth",
    },
    {
      id: 6,
      file: "avatar/face/006.webp",
      original: "nasty_naughty.webp",
      label: "Nasty Naughty",
      slug: "nasty-naughty",
      alt: "Nasty Naughty",
    },
    {
      id: 7,
      file: "avatar/face/007.webp",
      original: "oh_mouth.webp",
      label: "Oh Mouth",
      slug: "oh-mouth",
      alt: "Oh Mouth",
    },
    {
      id: 8,
      file: "avatar/face/008.webp",
      original: "sly_mouth.webp",
      label: "Sly Mouth",
      slug: "sly-mouth",
      alt: "Sly Mouth",
    },
    {
      id: 9,
      file: "avatar/face/009.webp",
      original: "smug.webp",
      label: "Smug",
      slug: "smug",
      alt: "Smug",
    },
    {
      id: 10,
      file: "avatar/face/010.webp",
      original: "squiggle.webp",
      label: "Squiggle",
      slug: "squiggle",
      alt: "Squiggle",
    },
    {
      id: 11,
      file: "avatar/face/011.webp",
      original: "supa_angy_face.webp",
      label: "Supa Angy Face",
      slug: "supa-angy-face",
      alt: "Supa Angy Face",
    },
    {
      id: 12,
      file: "avatar/face/012.webp",
      original: "weird_mouth.webp",
      label: "Weird Mouth",
      slug: "weird-mouth",
      alt: "Weird Mouth",
    },
    {
      id: 13,
      file: "avatar/face/013.webp",
      original: "wink.webp",
      label: "Wink",
      slug: "wink",
      alt: "Wink",
    },
    {
      id: 14,
      file: "avatar/face/014.webp",
      original: "yelling_face.webp",
      label: "Yelling Face",
      slug: "yelling-face",
      alt: "Yelling Face",
    },
  ],
  left: [
    {
      id: 1,
      file: "avatar/left/001.webp",
      original: "baguette.webp",
      label: "Baguette",
      slug: "baguette",
      alt: "Baguette",
    },
    {
      id: 2,
      file: "avatar/left/002.webp",
      original: "bubble_tea.webp",
      label: "Bubble Tea",
      slug: "bubble-tea",
      alt: "Bubble Tea",
    },
    {
      id: 3,
      file: "avatar/left/003.webp",
      original: "carrot.webp",
      label: "Carrot",
      slug: "carrot",
      alt: "Carrot",
    },
    {
      id: 4,
      file: "avatar/left/004.webp",
      original: "deodorant.webp",
      label: "Deodorant",
      slug: "deodorant",
      alt: "Deodorant",
    },
    {
      id: 5,
      file: "avatar/left/005.webp",
      original: "fish.webp",
      label: "Fish",
      slug: "fish",
      alt: "Fish",
    },
    {
      id: 6,
      file: "avatar/left/006.webp",
      original: "matcha.webp",
      label: "Matcha",
      slug: "matcha",
      alt: "Matcha",
    },
    {
      id: 7,
      file: "avatar/left/007.webp",
      original: "moon_wand.webp",
      label: "Moon Wand",
      slug: "moon-wand",
      alt: "Moon Wand",
    },
    {
      id: 8,
      file: "avatar/left/008.webp",
      original: "red_bull_can.webp",
      label: "Red Bull Can",
      slug: "red-bull-can",
      alt: "Red Bull Can",
    },
    {
      id: 9,
      file: "avatar/left/009.webp",
      original: "star_wand.webp",
      label: "Star Wand",
      slug: "star-wand",
      alt: "Star Wand",
    },
    {
      id: 10,
      file: "avatar/left/010.webp",
      original: "sword.webp",
      label: "Sword",
      slug: "sword",
      alt: "Sword",
    },
    {
      id: 11,
      file: "avatar/left/011.webp",
      original: "tote.webp",
      label: "Tote",
      slug: "tote",
      alt: "Tote",
    },
    {
      id: 12,
      file: "avatar/left/012.webp",
      original: "trophie.webp",
      label: "Trophie",
      slug: "trophie",
      alt: "Trophie",
    },
  ],
  right: [
    {
      id: 1,
      file: "avatar/right/001.webp",
      original: "baguette.webp",
      label: "Baguette",
      slug: "baguette",
      alt: "Baguette",
    },
    {
      id: 2,
      file: "avatar/right/002.webp",
      original: "bubble_tea.webp",
      label: "Bubble Tea",
      slug: "bubble-tea",
      alt: "Bubble Tea",
    },
    {
      id: 3,
      file: "avatar/right/003.webp",
      original: "carrot.webp",
      label: "Carrot",
      slug: "carrot",
      alt: "Carrot",
    },
    {
      id: 4,
      file: "avatar/right/004.webp",
      original: "deodorant.webp",
      label: "Deodorant",
      slug: "deodorant",
      alt: "Deodorant",
    },
    {
      id: 5,
      file: "avatar/right/005.webp",
      original: "fish.webp",
      label: "Fish",
      slug: "fish",
      alt: "Fish",
    },
    {
      id: 6,
      file: "avatar/right/006.webp",
      original: "matcha.webp",
      label: "Matcha",
      slug: "matcha",
      alt: "Matcha",
    },
    {
      id: 7,
      file: "avatar/right/007.webp",
      original: "moon_wand.webp",
      label: "Moon Wand",
      slug: "moon-wand",
      alt: "Moon Wand",
    },
    {
      id: 8,
      file: "avatar/right/008.webp",
      original: "red_bull_can.webp",
      label: "Red Bull Can",
      slug: "red-bull-can",
      alt: "Red Bull Can",
    },
    {
      id: 9,
      file: "avatar/right/009.webp",
      original: "star_wand.webp",
      label: "Star Wand",
      slug: "star-wand",
      alt: "Star Wand",
    },
    {
      id: 10,
      file: "avatar/right/010.webp",
      original: "sword.webp",
      label: "Sword",
      slug: "sword",
      alt: "Sword",
    },
    {
      id: 11,
      file: "avatar/right/011.webp",
      original: "tote.webp",
      label: "Tote",
      slug: "tote",
      alt: "Tote",
    },
    {
      id: 12,
      file: "avatar/right/012.webp",
      original: "trophie.webp",
      label: "Trophie",
      slug: "trophie",
      alt: "Trophie",
    },
  ],
  body: [
    {
      id: 1,
      file: "avatar/body/001.webp",
      original: "blue.webp",
      label: "Blue",
      slug: "blue",
      alt: "Blue",
    },
    {
      id: 2,
      file: "avatar/body/002.webp",
      original: "green.webp",
      label: "Green",
      slug: "green",
      alt: "Green",
    },
    {
      id: 3,
      file: "avatar/body/003.webp",
      original: "orange.webp",
      label: "Orange",
      slug: "orange",
      alt: "Orange",
    },
    {
      id: 4,
      file: "avatar/body/004.webp",
      original: "pink.webp",
      label: "Pink",
      slug: "pink",
      alt: "Pink",
    },
    {
      id: 5,
      file: "avatar/body/005.webp",
      original: "purple.webp",
      label: "Purple",
      slug: "purple",
      alt: "Purple",
    },
    {
      id: 6,
      file: "avatar/body/006.webp",
      original: "red.webp",
      label: "Red",
      slug: "red",
      alt: "Red",
    },
    {
      id: 7,
      file: "avatar/body/007.webp",
      original: "yellow.webp",
      label: "Yellow",
      slug: "yellow",
      alt: "Yellow",
    },
  ],
  hat: [
    {
      id: 1,
      file: "avatar/hat/001.webp",
      original: "barrette.webp",
      label: "Barrette",
      slug: "barrette",
      alt: "Barrette",
    },
    {
      id: 2,
      file: "avatar/hat/002.webp",
      original: "bear_hat.webp",
      label: "Bear Hat",
      slug: "bear-hat",
      alt: "Bear Hat",
    },
    {
      id: 3,
      file: "avatar/hat/003.webp",
      original: "bow_tie.webp",
      label: "Bow Tie",
      slug: "bow-tie",
      alt: "Bow Tie",
    },
    {
      id: 4,
      file: "avatar/hat/004.webp",
      original: "cowboy_hat.webp",
      label: "Cowboy Hat",
      slug: "cowboy-hat",
      alt: "Cowboy Hat",
    },
    {
      id: 5,
      file: "avatar/hat/005.webp",
      original: "crown.webp",
      label: "Crown",
      slug: "crown",
      alt: "Crown",
    },
    {
      id: 6,
      file: "avatar/hat/006.webp",
      original: "duck.webp",
      label: "Duck",
      slug: "duck",
      alt: "Duck",
    },
    {
      id: 7,
      file: "avatar/hat/007.webp",
      original: "efficiency_hat.webp",
      label: "Efficiency Hat",
      slug: "efficiency-hat",
      alt: "Efficiency Hat",
    },
    {
      id: 8,
      file: "avatar/hat/008.webp",
      original: "flower.webp",
      label: "Flower",
      slug: "flower",
      alt: "Flower",
    },
    {
      id: 9,
      file: "avatar/hat/009.webp",
      original: "frog_hat.webp",
      label: "Frog Hat",
      slug: "frog-hat",
      alt: "Frog Hat",
    },
    {
      id: 10,
      file: "avatar/hat/010.webp",
      original: "grad_cap.webp",
      label: "Grad Cap",
      slug: "grad-cap",
      alt: "Grad Cap",
    },
    {
      id: 11,
      file: "avatar/hat/011.webp",
      original: "hw_cap.webp",
      label: "Hw Cap",
      slug: "hw-cap",
      alt: "Hw Cap",
    },
    {
      id: 12,
      file: "avatar/hat/012.webp",
      original: "kitten_headset.webp",
      label: "Kitten Headset",
      slug: "kitten-headset",
      alt: "Kitten Headset",
    },
    {
      id: 13,
      file: "avatar/hat/013.webp",
      original: "leaf.webp",
      label: "Leaf",
      slug: "leaf",
      alt: "Leaf",
    },
    {
      id: 14,
      file: "avatar/hat/014.webp",
      original: "luffy_straw_hat.webp",
      label: "Luffy Straw Hat",
      slug: "luffy-straw-hat",
      alt: "Luffy Straw Hat",
    },
    {
      id: 15,
      file: "avatar/hat/015.webp",
      original: "party_hat_1.webp",
      label: "Party Hat 1",
      slug: "party-hat-1",
      alt: "Party Hat 1",
    },
    {
      id: 16,
      file: "avatar/hat/016.webp",
      original: "party_hat_2.webp",
      label: "Party Hat 2",
      slug: "party-hat-2",
      alt: "Party Hat 2",
    },
    {
      id: 17,
      file: "avatar/hat/017.webp",
      original: "pirate.webp",
      label: "Pirate",
      slug: "pirate",
      alt: "Pirate",
    },
    {
      id: 18,
      file: "avatar/hat/018.webp",
      original: "pylon.webp",
      label: "Pylon",
      slug: "pylon",
      alt: "Pylon",
    },
    {
      id: 19,
      file: "avatar/hat/019.webp",
      original: "stinky.webp",
      label: "Stinky",
      slug: "stinky",
      alt: "Stinky",
    },
    {
      id: 20,
      file: "avatar/hat/020.webp",
      original: "tiara.webp",
      label: "Tiara",
      slug: "tiara",
      alt: "Tiara",
    },
    {
      id: 21,
      file: "avatar/hat/021.webp",
      original: "top_hat.webp",
      label: "Top Hat",
      slug: "top-hat",
      alt: "Top Hat",
    },
    {
      id: 22,
      file: "avatar/hat/022.webp",
      original: "viking.webp",
      label: "Viking",
      slug: "viking",
      alt: "Viking",
    },
    {
      id: 23,
      file: "avatar/hat/023.webp",
      original: "witch_hat.webp",
      label: "Witch Hat",
      slug: "witch-hat",
      alt: "Witch Hat",
    },
  ],
};

export default avatarManifest;
