const MAIN = "main";
const WORKSHOP = "workshop";
const ACTIVITY = "activity";
const FOOD = "food";
const SPON_BOOTH = "spon_booth";
const SPONSOR = "sponsor";
const TH_ATRIUM = "TH Atrium";
const SM_ATRIUM = "SM Atrium";
const SH_ATRIUM = "SH Atrium";

export interface Event {
  name: string;
  category: "main" | "workshop" | "activity" | "food" | "spon_booth" | "all";
  location?: string;
  desc?: string;
  workshop_type?: "sponsor" | "other";
  day: 1 | 2 | 3;
  start: string;
  end?: string;
}

export const schedule: Event[] = [
  {
    name: "Registration",
    category: MAIN,
    location: "Lucy's Cafe",
    day: 1,
    start: "17:00",
    end: "19:00",
  },
  {
    name: "Dinner",
    category: FOOD,
    location: TH_ATRIUM,
    day: 1,
    start: "17:00",
    end: "19:00",
  },
  {
    name: "Sponsor Bay Open",
    category: SPON_BOOTH,
    location: SM_ATRIUM,
    day: 1,
    start: "17:00",
    end: "23:00",
  },
  {
    name: "Opening Ceremony",
    category: "all",
    location: "BMO Auditorium Ivey",
    day: 1,
    start: "19:00",
    end: "20:00",
  },
  {
    name: "Hacking Begins",
    category: MAIN,
    day: 1,
    start: "22:00",
  },
  {
    name: "Team Formation Workshop",
    category: WORKSHOP,
    workshop_type: "other",
    location: "SM 2316",
    day: 1,
    start: "22:00",
    end: "23:00",
  },
  {
    name: "Google Developer Student Club Workshop",
    category: WORKSHOP,
    workshop_type: "other",
    location: "SM 2317",
    day: 1,
    start: "23:00",
  },
  {
    name: "Movie Night",
    category: ACTIVITY,
    location: "SM 3345",
    day: 1,
    start: "23:00",
  },
  {
    name: "Hardware Lab",
    category: ACTIVITY,
    location: "TH 3190",
    day: 1,
    start: "22:00",
  },
  {
    name: "Hacking",
    category: MAIN,
    day: 2,
    start: "00:00",
  },
  {
    name: "Movie Night",
    category: ACTIVITY,
    location: "SM 3345",
    day: 2,
    start: "00:00",
    end: "02:00",
  },
  {
    name: "Midnight Snack",
    category: FOOD,
    location: TH_ATRIUM,
    day: 2,
    start: "00:00",
    end: "01:00",
  },
  {
    name: "Breakfast",
    category: FOOD,
    location: TH_ATRIUM,
    day: 2,
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Sponsor Bay Open",
    category: SPON_BOOTH,
    location: SM_ATRIUM,
    day: 2,
    start: "09:00",
    end: "23:30",
  },
  {
    name: "Hardware Lab",
    category: ACTIVITY,
    location: "TH 3190",
    day: 2,
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Coffee Chats",
    category: ACTIVITY,
    location: SH_ATRIUM,
    day: 2,
    start: "10:00",
    end: "14:00",
  },
  {
    name: "MLH Figma Workshop",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2316",
    day: 2,
    start: "10:00",
    end: "11:00",
  },
  {
    name: "Canada Life Workshop",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2317",
    day: 2,
    start: "11:30",
    end: "12:00",
  },
  {
    name: "TD Invent",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2317",
    day: 2,
    start: "12:30",
    end: "13:00",
  },
  {
    name: "Canada Life Workshop",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2316",
    day: 2,
    start: "13:30",
    end: "14:00",
  },
  {
    name: "Sun Life Workshop",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2316",
    day: 2,
    start: "15:30",
    end: "16:00",
  },
  {
    name: "Sun Life Workshop",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2316",
    day: 2,
    start: "20:00",
    end: "20:30",
  },
  {
    name: "Underrepresented Genders and Their Allies",
    category: WORKSHOP,
    workshop_type: "other",
    location: "SM 3345",
    day: 2,
    start: "15:00",
    end: "16:00",
  },
  {
    name: "Morning Yoga",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "09:00",
    end: "9:30",
  },
  {
    name: "Mural Colouring",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "10:00",
    end: "10:30",
  },
  {
    name: "Bracelet Making",
    category: ACTIVITY,
    location: "SM 3317",
    day: 2,
    start: "11:00",
    end: "11:30",
  },
  {
    name: "Slime Making",
    category: ACTIVITY,
    location: "SM 3317",
    day: 2,
    start: "17:00",
    end: "18:00",
  },
  {
    name: "Cup Stacking",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "19:00",
    end: "20:00",
  },
  {
    name: "Fire Noodle",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "21:00",
    end: "22:00",
  },
  {
    name: "Karaoke",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "23:00",
  },
  {
    name: "Postcard Making",
    category: ACTIVITY,
    location: TH_ATRIUM,
    day: 2,
    start: "23:00",
    end: "23:30",
  },
  {
    name: "Lunch",
    category: FOOD,
    location: TH_ATRIUM,
    day: 2,
    start: "12:00",
    end: "14:00",
  },
  {
    name: "Dinner",
    category: FOOD,
    location: TH_ATRIUM,
    day: 2,
    start: "18:00",
    end: "20:00",
  },
  {
    name: "Midnight Snack",
    category: FOOD,
    location: TH_ATRIUM,
    day: 3,
    start: "00:00",
    end: "02:00",
  },
  {
    name: "Judging Workshop [HACK WESTERN]",
    category: WORKSHOP,
    workshop_type: SPONSOR,
    location: "SM 2317",
    day: 3,
    start: "10:00",
    end: "10:30",
  },
  {
    name: "Hacking Ends @ 10 AM",
    category: MAIN,
    day: 3,
    start: "09:30",
    end: "10:00",
  },
  {
    name: "Demo Fair + Judging",
    category: MAIN,
    day: 3,
    start: "10:30",
    end: "12:30",
  },
  {
    name: "Therapy Dogs",
    category: ACTIVITY,
    location: SM_ATRIUM,
    day: 3,
    start: "12:00",
    end: "13:00",
  },
  {
    name: "Breakfast",
    category: FOOD,
    location: TH_ATRIUM,
    day: 3,
    start: "08:00",
    end: "10:00",
  },
  {
    name: "Lunch",
    category: FOOD,
    location: TH_ATRIUM,
    day: 3,
    start: "11:00",
    end: "13:00",
  },
  {
    name: "Closing Ceremony",
    category: "all",
    location: "BMO Auditorium Ivey",
    day: 3,
    start: "13:00",
    end: "15:00",
  },
];
