export interface SponsorLogoProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  x: number;
  y: number;
  rotation: number;
  href: string;
}

const prefix = "/sponsors/";

export const SPONSORS: readonly SponsorLogoProps[] = [
  {
    src: `${prefix}scotiabank.png`,
    alt: "Scotiabank",
    width: 448,
    height: 87,
    x: 200,
    y: 28,
    rotation: 0,
    href: "https://www.scotiabank.com",
  },
  {
    src: `${prefix}canadalife.png`,
    alt: "Canada Life",
    width: 312,
    height: 108,
    x: 520,
    y: 260,
    rotation: 0,
    href: "https://www.canadalife.com",
  },
  {
    src: `${prefix}accenture.png`,
    alt: "Accenture",
    width: 290,
    height: 86,
    x: 530,
    y: 465,
    rotation: 0,
    href: "https://www.accenture.com/ca-en",
  },
  {
    src: `${prefix}pg.png`,
    alt: "P&G",
    width: 144,
    height: 55,
    x: 330,
    y: 480,
    rotation: 0,
    href: "https://www.pg.ca/en-ca/",
  },
  {
    src: `${prefix}sunlife.png`,
    alt: "Sun Life",
    width: 345,
    height: 72,
    x: 475,
    y: 140,
    rotation: 0.4,
    href: "https://www.sunlife.ca",
  },
  {
    src: `${prefix}manulife.png`,
    alt: "Manulife",
    width: 398,
    height: 82,
    x: 25,
    y: 150,
    rotation: -0.2,
    href: "https://www.manulife.ca",
  },
  {
    src: `${prefix}meta.png`,
    alt: "Meta",
    width: 230,
    height: 160,
    x: 50,
    y: 480,
    rotation: 0,
    href: "https://www.meta.com",
  },
  {
    src: `${prefix}awake.png`,
    alt: "Awake Caffeinated Chocolate",
    width: 200,
    height: 200,
    x: 20 ,
    y: 240,
    rotation: 0,
    href: "https://www.awakechocolate.com",
  },
  {
    src: `${prefix}leuchtturm.png`,
    alt: "Leuchtturm 1917",
    width: 200,
    height: 34,
    x: 40,
    y: 395,
    rotation: 0,
    href: "https://www.leuchtturm1917.ca/",
  },
  {
    src: `${prefix}warp.png`,
    alt: "Warp",
    width: 180,
    height: 35,
    x: 380,
    y: 400,
    rotation: 0,
    href: "https://www.warp.dev/",
  },
  {
    src: `${prefix}cse.png`,
    alt: "Communications Security Establishment Canada",
    width: 80,
    height: 80,
    x: 280,
    y: 380,
    rotation: 0,
    href: "https://www.cse-cst.gc.ca/en",
  },
  {
    src: `${prefix}wts.png`,
    alt: "Western Technology Services",
    width: 70,
    height: 180,
    x: 280,
    y: 240,
    rotation: 0,
    href: "https://wts.uwo.ca/index.html",
  },
  {
    src: `${prefix}morrissette.png`,
    alt: "Western Morrissette Institute for Entrepreneurship",
    width: 180,
    height: 100,
    x: 610,
    y: 405,
    rotation: 0,
    href: "https://entrepreneurship.uwo.ca//",
  },
];
