name: Prettify
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
      - name: Run prettier
        run: npx prettier --write ./src
      - name: Commit changes
        id: commit
        run: |
          git config --global user.email 'prettify-hackwestern[bot]@users.noreply.github.com'
          git config --global user.name 'prettify-hackwestern[bot]'
          git add src
          if ! git diff --cached --quiet; then
            git commit -m "Prettify code"
            git push origin HEAD:${{ github.head_ref }}
            echo "trigger_test=true" >> "$GITHUB_OUTPUT"
          else
            echo "trigger_test=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Trigger Test workflow
        if: steps.commit.outputs.trigger_test == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: test

