name: Prettify
on:
  pull_request:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"
      - name: Pull changes
        run: git pull origin ${{ github.head_ref || github.ref_name }}
      - name: Install prettier
        run: npm install prettier
      - name: Run prettier
        run: npx prettier --check ./src
      - name: Commit changes
        run: |
          git config --global user.email 'prettify[bot]@users.noreply.github.com'
          git config --global user.name 'prettify [bot]'
          git checkout -b ${{ github.head_ref || github.ref_name }}
          git add .
          git commit -m "Prettify code"
      - name: Push changes
        run: git push origin ${{ github.head_ref || github.ref_name }}