name: Prettify
on:
  push:
    branches:
      - prettier
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"
      - name: Install prettier
        run: npm install --no-package-lock --no-save prettier@latest
      - name: Run prettier
        run: npx prettier --write ./src
      - name: Commit and push changes
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add .
          git commit -m "Prettify code"
          git push