name: Test
on:
  repository_dispatch:
    types: [test]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: "http://localhost:3000"
      GITHUB_CLIENT_ID: ${{ secrets.NEXTAUTH_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.NEXTAUTH_GITHUB_CLIENT_SECRET }}
      DISCORD_CLIENT_ID: ${{ secrets.NEXTAUTH_DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.NEXTAUTH_DISCORD_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.NEXTAUTH_GOOGLE_CLIENT_SECRET }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    steps:
      - name: Pick ref
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "ref=${{ github.event.client_payload.sha }}" >>"$GITHUB_OUTPUT"
          else # pull_request / manual dispatch
            echo "ref=${{ github.head_ref }}" >>"$GITHUB_OUTPUT"
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run tests
        run: npx vitest
