name: Test and Build
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: npm install

      # for when we have tests
      # - name: Run tests
      #  run: npm test

      - name: Build
        run: npm run build